# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  # Make 4 clients for our AD Environment
  for i in 1..4 do
    config.vm.define "client-#{i}" do |client_computer|
      client_computer.vm.box = "StefanScherer/windows_10"
      client_computer.vm.hostname = "client-#{i}"


      client_computer.vm.provider "vmware_workstation" do |vmware_provider|
        vmware_provider.memory = 4096
        vmware_provider.cpus = 2

        #vmware_provider.vmx["ethernet0.connectionType"] = "nat"
      end # End the Provider specifications

    end # End the config definition

  end # End of For Lopp...

end # End of vagrant File
