# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

# make 3 configuration targets.
  for i in 1..3 do
    config.vm.define "node-#{i}" do |node|
      
      # Define the "base image" and the hostname for the VM
      node.vm.box = "generic/ubuntu2004"
      node.vm.hostname = "node-#{i}"
      node.vm.network :private_network, type: "dhcp"

      # Ask vmware_workstaion to make the following changes...
      node.vm.provider "vmware_workstation" do |vm|
      
        # configure the VM to have 1 core and 2GB of ram
        vm.memory = 2048
        vm.cpus = 1
    
      end

      # Patch the Target
      #node.vm.provision "shell", inline: "apt -y update && apt -y upgrade"

    # End of the Virtual Machine Definition
    end

  # End of the loop
  end

# Make 1 Ansible host.
  for i in 1..1 do
  
    # Start the Definition of the VM we want created, ansible_server
    config.vm.define "ansible-#{i}" do |ansible_server|

      # Use the generic ubuntu 2004 base image and set the hostname
      ansible_server.vm.box = "generic/ubuntu2004"
      ansible_server.vm.hostname = "ansible-#{i}"
      ansible_server.vm.network :private_network, type: "dhcp"

      # Ask vmware_workstation to make the following changes...
      ansible_server.vm.provider "vmware_workstation" do |ansible_server_provider|

        # Configure the VM to have 2 cores and 4GB of ram
        ansible_server_provider.memory = 4096
        ansible_server_provider.cpus = 2

      end

      # Install Ansible on the host VM
      ansible_server.vm.provision "shell", inline: "apt install -y ansible"

    # End of the Virtual Machine Config
    end

  # End of Andible Loop
  end
  
# End of the Vagrant File.
end
